### ISSUE TITLE
Glossary Term's Related Entities (Column) would show incorrect imformation in UI when it inherited by others

### ISSUE THREAD

**Issue by HolgerWang1999** [datahub-project/datahub#10264]
**Describe the bug**
Glossary Term's Related Entities (Column) would show incorrect imformation in UI when it inherited by others
Before inherited by: Matched column term
After inherited by: 'Matched column term' disappeared

**To Reproduce**
1. There is a Glossary Term named '销售额'，it was added to a table's column(dws_trade_mall_id.sales_amount)
![image](https://github.com/datahub-project/datahub/assets/128286646/29130b90-abaa-42b8-8b4a-9412d7f82993)

2. Create a new Glossary Term named '渠道销售额' which inherited '销售额'
![image](https://github.com/datahub-project/datahub/assets/128286646/c84263a2-d4e4-4a11-ac04-3bd976e5a8af)

**Expected behavior**
The Relationship between Glossary Term named '销售额' should be the same as before

**Screenshots**
But  'Matched column term' disappeared
![image](https://github.com/datahub-project/datahub/assets/128286646/e635140f-f22d-41ad-bb2f-fba5025bbfe5)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Microsoft Edge
 - Version: v0.11.0

**Additional context**

**Comment by jjoyce0510** [comment]
Basically the problem is that:

When adding a related entity to a glossary term, it changes the related entities hint to remove the "matches column term" piece? 

It's unclear to me how this is possible since the whole concept of Related terms is completely separate from those match hints you are seeing on the search card. Is it possible that you changed the relationship between the term and the entity to move the term to the entity level?

**Comment by HolgerWang1999** [comment]
I didn't change the relationship between the term and the entity to move the term to the entity level.
The the related entities hint just changed after I add an inherited-by relation between terms.
