### ISSUE TITLE
Values of structured properties assigned to schema field entity is not editable via UI.

### ISSUE THREAD

**Issue by deepgarg-visa** [datahub-project/datahub#11414]
**Describe the bug**
Values of structured properties assigned to schema field entity is not editable via UI. 

**To Reproduce**
All steps have been performed by User with Admin role
1. Create structured properties through CLI
2. associate properties to schemaField entity by openapi endpoint
3. properties visible in UI but edit the values options is not visible

**Expected behavior**
Similar to properties associated with dataset, users can also edit the values of structured properties associated with schema field via UI

**Screenshots**
Dataset
<img width="1715" alt="Screenshot 2024-09-17 at 9 52 41 PM" src="https://github.com/user-attachments/assets/38063c05-774f-4b53-ae04-5dc13bf76753">

Schema Field
<img width="1715" alt="Screenshot 2024-09-17 at 10 19 52 PM" src="https://github.com/user-attachments/assets/eb6f9255-b146-4d13-a198-259b7e3ed086">

**Datahub version
 - 13.3

**Comment by chriscollins3456** [comment]
hey @deepgarg-visa! This functionality was actually only added in the most recent release with `v0.14.0.2`. If you upgrade your instance you should be able to see this now:
<img width="588" alt="image" src="https://github.com/user-attachments/assets/e2c7e4ff-3685-4e5a-8548-84498ebfb1a7">

I'm going to close this issue for now since it should be resolved in a newer version. Feel free to re-open if you see another issue related to this

**Comment by deepgarg-visa** [comment]
Thanks @chriscollins3456. We will upgrade and let you know
