### ISSUE TITLE
[UI Ingestion] Why UI Ingestion not support custom ingestion Source?

### ISSUE THREAD

**Issue by wangqinghuan** [datahub-project/datahub#4088]
[ui-ingestion](https://datahubproject.io/docs/ui-ingestion) says custom ingestion Source can not be supported.

**Comment by jjoyce0510** [comment]
It does not support custom sources because we fetch the DataHub CLI repositories from PyPI, which means that the package has to be published somewhere centrally.

**Comment by anshbansal** [comment]
No we cannot do that currently. Ingestion runs inside virtual env. For questions/discussions please head to https://slack.datahubproject.io/

**Comment by HynekBlaha** [comment]
I was able to make run custom integration via UI in Datahub Kubernetes.
I had to build my own image
```dockerfile
# Dockerfile for custom DataHub ingestion image with Dagster GraphQL source
FROM acryldata/datahub-actions:v1.3.0

# Set working directory in home where datahub user has permissions
WORKDIR /home/datahub/my-datahub

# Copy source code and configuration
COPY --chown=datahub:datahub pyproject.toml uv.lock ./
COPY --chown=datahub:datahub my_datahub ./my_datahub

# Install the custom source plugin
RUN uv pip install -e .

# Verify installation
RUN python -c "from my_datahub.sources import MyDatahubSource; print('✅')"

# Reset working directory
WORKDIR /
```

Register entrypoint in pyproject.toml:
```
[project.entry-points."datahub.ingestion.source.plugins"]
my-datahub-source = "my_datahub.sources:MyDatahubSource"
```

UI Recipe:
```
source:
    type: my-datahub-source
    config: {}
```
UI Config:
<img width="1133" height="666" alt="Image" src="https://github.com/user-attachments/assets/9fbdd7ea-5bcf-4d2c-84db-527cb66f263e" />

It is important to set `CLI Version=native` to use image venv instead of spawning new subprocess which will lead to creating frest venv.
