### ISSUE TITLE
Cannot Recreate Dataset After Hard Delete

### ISSUE THREAD

**Issue by eeepmb** [datahub-project/datahub#4413]
Hi all,
during development I tried to delete and recreate a dataset. But when executing the code below again after the delete I cannot find the dataset in the UI. 
I would expect DataHub to recreate the dataset or at least give some sort of feedback.
However in the database the entry remains `{"removed":true}` as you can see at the bottom.

```python
import datahub.emitter.mce_builder as builder
from datahub.emitter.rest_emitter import DatahubRestEmitter

def datasetUrn(tbl):
    return builder.make_dataset_urn("bigquery", tbl, "DEV")

# Construct a lineage object.
lineage_mce = builder.make_lineage_mce(
    [
        datasetUrn("bar2"),
        datasetUrn("bar4")
    ],
    datasetUrn("bar"),
)

# Create an emitter to the GMS REST API.
emitter = DatahubRestEmitter("http://localhost:8080")

# Emit metadata!
emitter.emit_mce(lineage_mce)
```

`datahub delete --env DEV --entity_type dataset --platform bigquery -f`

-> Execute Python code again.

```
MySQL [datahub]> select * from metadata_aspect_v2 where urn = "urn:li:dataset:(urn:li:dataPlatform:bigquery,bar,DEV)" and metadata = "{\"removed\":true}";
+-------------------------------------------------------+--------+---------+------------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------+-------------------------+------------+
| urn                                                   | aspect | version | metadata         | systemmetadata                                                                                                          | createdon                  | createdby               | createdfor |
+-------------------------------------------------------+--------+---------+------------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------+-------------------------+------------+
| urn:li:dataset:(urn:li:dataPlatform:bigquery,bar,DEV) | status |       0 | {"removed":true} | {"registryVersion":"0.0.0.0-dev","runId":"delete-run-id","registryName":"unknownRegistry","lastObserved":1647336916742} | 2022-03-15 09:35:17.403000 | urn:li:corpuser:UNKNOWN | NULL       |
+-------------------------------------------------------+--------+---------+------------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------+-------------------------+------------+
```

* DataHub Frontend ﻿v0.8.28
* DataHub CLI v. 0.8.29
* MySQL v 5.7.37

Also when trying in ingest to a different environment (e.g. TST) I run into the error `Caused by: java.net.URISyntaxException: Invalid URN Parameter: 'No enum constant com.linkedin.common.FabricType.TST: urn:li:dataset:(urn:li:dataPlatform:bigquery,bar,TST)`.
Is there documented which environments are accepted? (I would find it more user centric to be able to choose this freely)

**Comment by pedro93** [comment]
Hello @eeepmb!

Thank you submitting this issue!
First of all, this looks like a bug. Did you run this code on a clean deployment?

Second...

The reason why your ingested dataset is not appearing in the UI is because of the {"removed":true}. 
This is called a soft-deleted entity which you can learn more about [in our docs on deleting metadata](https://datahubproject.io/docs/how/delete-metadata).

What you are seeing in MySQL is all aspects for urn `"urn:li:dataset:(urn:li:dataPlatform:bigquery,bar,DEV)"` that have the `removed:true`. Only the [Status](https://github.com/datahub-project/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/common/Status.pdl) aspect has that property. It is a special aspect in DataHub to mark entities (i.e: Dataset, Dashboard, User, DataJob, etc...) that have been deleted.

Looking at your code I would suggest using MCPs (MetadataChangeProposal) and not MCEs (MetadataChangeEvent) as the latter is deprecated as of v0.8.7. See this [doc on MCEs & MAEs vs MCP & MCLs](https://datahubproject.io/docs/advanced/mcp-mcl). 

About the supported environments, they are defined in the [FabricType.pdl](https://github.com/datahub-project/datahub/blob/master/li-utils/src/main/pegasus/com/linkedin/common/FabricType.pdl) file so you can see there which ones are available. About defining your own environments, I suggest you take a look at [how to extend the metadata model](https://datahubproject.io/docs/metadata-modeling/extending-the-metadata-model) in particular step 3.

**Comment by eeepmb** [comment]
Hi @pedro93,
thanks for the feedback and background info. 

We ran this code on a clean deployment in the first place but now we have a few of those entries in the DB..

I must admit that I fogot to do a hard delete in this example but we experienced this behaviour with hard deletes too:

```
$ datahub delete --env DEV --entity_type dataset --platform bigquery -f --hard

...

MySQL [datahub]> select * from metadata_aspect_v2 where urn = "urn:li:dataset:(urn:li:dataPlatform:bigquery,bar,DEV)" and metadata = "{\"removed\":true}";
+-------------------------------------------------------+--------+---------+------------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------+-------------------------+------------+
| urn                                                   | aspect | version | metadata         | systemmetadata                                                                                                          | createdon                  | createdby               | createdfor |
+-------------------------------------------------------+--------+---------+------------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------+-------------------------+------------+
| urn:li:dataset:(urn:li:dataPlatform:bigquery,bar,DEV) | status |       0 | {"removed":true} | {"registryVersion":"0.0.0.0-dev","runId":"delete-run-id","registryName":"unknownRegistry","lastObserved":1647336916742} | 2022-03-15 09:35:17.403000 | urn:li:corpuser:UNKNOWN | NULL       |
+-------------------------------------------------------+--------+---------+------------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------+-------------------------+------------+
1 row in set (0.00 sec)
```

For this example I grabbed lineage_emitter_rest.py from [the samples](https://datahubproject.io/docs/lineage/sample_code/) with slight changes. You might mentioned it is depreciated or update the code accordingly.

Looking forward to hear from you about your findings.

**Comment by pedro93** [comment]
Hey @eeepmb 

I've run your code locally on the master branch (commit id: ad039aab6) and I was not able to reproduce your error.
This may be a bug that has since been fixed. We are looking to do a release today or tomorrow so could you wait for that?

These are the steps I took to reproduce your issue:
1.) Run python script that ingests a dataset with lineage info.

2.) Go to DataHub UI and validate that dataset is present.

3.) Dry-run soft delete of dataset to see what would be deleted: `datahub delete --env DEV --entity_type dataset --platform bigquery --dry-run` => Got correct info, would delete **urn:li:dataset:(urn:li:dataPlatform:bigquery,bar,DEV)**.

4.) Using [ElasticVue](https://chrome.google.com/webstore/detail/elasticvue/hkedbapjpblbodpgbajblpnlpenaebaa) chrome plugin, investigate elastic search index of datasets to confirm dataset is there. It should be since we use Elasticsearch as ou searching index, if it's not there we would not be able to search for it in the UI.

5.) Perform a hard delete of the dataset: ` datahub delete --env DEV --entity_type dataset --platform bigquery --hard`

6.) Check Elasticsearch, dataset is no longer in dataset index.

7.) Re-run script to ingest dataset.

8.) Check Elastic, dataset is present.

9.) **Soft delete** the dataset: `datahub delete --env DEV --entity_type dataset --platform bigquery --soft`

10.) Check Elastic, dataset is present **with** a new field (removed: true) which marks the entity as soft deleted and so unsearchable in the UI.

11.) Re-run script to ingest dataset.

12.) Check Elastic, dataset is present **without** removed property. Document is now searchable in the UI, as expected.


About the code samples you mentioned, they are indeed outdated. 
I've opened a ticket internally to update them, a GitHub issue will follow soon. In the meantime I suggest you look at https://datahubproject.io/docs/metadata-ingestion/as-a-library/ for inspiration.

Thanks!

**Comment by eeepmb** [comment]
Hi @pedro93, 
I migrated our cluster to v.0.8.31 and everything is working as expect now. 
However removing leftovers from before in the DB and Elasticsearch wasn't possible by using the DataHub CLI. 
So for now I deleted the entries in the DB manually. 

Can you guide me to delete left references in Elasticsearch? I want to avoid redeploying everything.

I'll close the issue afterwards.
Thanks in advance.

**Comment by pedro93** [comment]
Hello @eeepmb 

What do you mean by?
`However removing leftovers from before in the DB and Elasticsearch wasn't possible by using the DataHub CLI`

If you manually deleted the entity from the DB you know need to delete it in elasticsearch. 
We have 1 index in elastic per entity, so if you ingested a dataset that you want to delete, then delete the corresponding record in the dataset_index. 

If you can access the elasticsearch cluster from your machine, I would suggest using something like: https://chrome.google.com/webstore/detail/elasticvue/hkedbapjpblbodpgbajblpnlpenaebaa to interact with elastic and see exactly what you are deleting.

**Comment by eeepmb** [comment]
Hi @pedro93,
after hard deleting other datasets with DataHub CLI I still found those entries from above in our DB since from DataHub POV these datasets did not exist anymore. 
So I deleted those entries in the DB and was hoping that Elasticsearch would update data accordingly. But I still find references in the DataHub UI. 

However it seems to be quicker for me to set up a fresh deployment than getting into Elasticsearch for now. 

Closing this for now. Thanks for the help! 

PS: I noticed that after [hard] deleting datasets you still find references in the UI (e.g. under recently viewed). Would be great if those references will be removed too as a feature soon.

**Comment by pedro93** [comment]
`after hard deleting other datasets with DataHub CLI I still found those entries from above in our DB since from DataHub POV these datasets did not exist anymore.`
Was this delete done after upgrading both the cli & datahub server deployment using the `--hard` parameter in the delete command? That is unexpected.

`So I deleted those entries in the DB and was hoping that Elasticsearch would update data accordingly. But I still find references in the DataHub UI.`
Unfortunately if you delete manually in the DB, there is no reconciliation logic in datahub to delete stuff in elastic. Even if we did have that logic, what database should be considered the ground truth? The relational DB or Elastic? Each serve different purposes so it would be non-trivial to re-create one against the other.

**Comment by eeepmb** [comment]
@pedro93 
1.) yes, both CLI & DataHub containers were updated. I tried deleting the entries by the commands below. But the entries remaind.

```
datahub delete --env dev --entity_type dataset --hard -f
datahub delete --platform bigquery --hard -f
datahub delete --entity_type dataset --hard -f
```

2.) I must admit that I had a misunderstanding here then. I supposed the relational DB to be the ground truth and Elastic being used to do additional tasks with the data in the DB. But I agree your argument.
