### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by loibucket** [datahub-project/datahub#4626]
**Describe the bug**
Trying to run datahub quickstart, getting these errors

ERROR: for datahub-frontend-react  no matching manifest for linux/amd64 in the manifest list entries
ERROR: for datahub-gms  no matching manifest for linux/amd64 in the manifest list entries

**To Reproduce**
1. Install datahub per official docs
2. run datahub docker quickstart 

**Expected behavior**
install success

**Screenshots**

**Desktop (please complete the following information):**
 - OS: debian
 - Browser none
 - Version 10

**Additional context**
Is it because in the docker hub, there is a "head" tag with nothing in it?
https://hub.docker.com/r/linkedin/datahub-gms/tags
https://hub.docker.com/r/linkedin/datahub-frontend-react/tags

**Comment by 812406210** [comment]
Friday ，i sucessed ,but now i install it ,it happened this issue , i will self-closing ,haha

**Comment by 812406210** [comment]
![image](https://user-images.githubusercontent.com/22192011/162597980-ba0e4d89-4c2c-4ce7-9886-ee2189b09ae9.png)
haha ,the issue  of answer  is here!

**Comment by IanHopkinson** [comment]
I have this issue too running on Windows 10

**Comment by pawel3275** [comment]
As a temporary fix:

If you are using ./quickstart.sh you can change the yml file called docker-compose-without-neo4j.quickstart.yml
In the datahub-gms section replace:
`image: linkedin/datahub-gms:${DATAHUB_VERSION:-head} `
with
`image: linkedin/datahub-gms:aa05faa`

Also replace in the datahub-frontend-react section replace:
`image: linkedin/datahub-frontend-react:${DATAHUB_VERSION:-head}`
with
`image: linkedin/datahub-frontend-react:aa05faa`

This will use last working images from docker. After saving the file simply run the ./quickstart.sh again

**Comment by loibucket** [comment]
> As a temporary fix:
> 
> If you are using ./quickstart.sh you can change the yml file called docker-compose-without-neo4j.quickstart.yml In the datahub-gms section replace: `image: linkedin/datahub-gms:${DATAHUB_VERSION:-head} ` with `image: linkedin/datahub-gms:aa05faa`
> 
> Also replace in the datahub-frontend-react section replace: `image: linkedin/datahub-frontend-react:${DATAHUB_VERSION:-head}` with `image: linkedin/datahub-frontend-react:aa05faa`
> 
> This will use last working images from docker. After saving the file simply run the ./quickstart.sh again

Where is this yml file located?

**Comment by IanHopkinson** [comment]
Looks like this has been fixed now, so no need for the workaround.

I'm a bit unclear as to the intent of quickstart. I use it as the beginner's/easy install of DataHub, and to develop against but the fact that it uses the HEAD versions of images and the docker-compose files rather than pinned release versions suggests it is more a demonstration of the cutting edge version of DataHub.

**Comment by shirshanka** [comment]
Hi @IanHopkinson : you are right that `quickstart` is intended to showcase the latest HEAD version of DataHub. 
We will be working on improving the CI docker pushes so that we don't have these kind of partial failures going forward. 

You might be already aware that you can always pin to a specific release version by issuing e.g.: 
`DATAHUB_VERSION=v0.8.33 datahub docker quickstart`

or setting the `DATAHUB_VERSION` env variable across all your sessions.

**Comment by shirshanka** [comment]
Closing as this seems to be a resolved thread.
