### ISSUE TITLE
Extended Glossary Metamodel not showing in UI

### ISSUE THREAD

**Issue by fprima** [datahub-project/datahub#4745]
Aspects added by extending the glossaryTerm meta model in v0.8.33 are not displaying in UI. I can see the new aspects doing a get.
I tried extending the dataset entity and that works fine.

This is how I defined the renderSpec in the aspect:
@Aspect = {
  "name": "customNewGlossaryAspect",
  "autoRender": true,
  "renderSpec": {
    "displayType": "tabular", // or properties
    "key": "newRecord",
    "displayName": "New Fields"
  }
}
record GlossaryAspect {
  newRecord: array[GlossaryAspectFields]
}

**Comment by maggiehays** [comment]
Hi @fprima! Right now, we only auto-render new aspects on Dataset entities, so this is expected behavior. Would you mind opening a [feature request](https://feature-requests.datahubproject.io/) for this support & provide some details about your use cases? 

As a temporary work-around, you can also pass in details as key-value pairs via the properties aspect. I'll close this out in the meantime!
