### ISSUE TITLE
Not possible to add same user with multiple owner types

### ISSUE THREAD

**Issue by Vladislaff** [datahub-project/datahub#4850]
**Describe the bug**
Not possible to add same user with multiple owner types via GUI.
Works through API though

**To Reproduce**
1. Open a dataset
2. Click on 'Add owner'
3. Choose Owner and Type
4. Click 'Add'
5. Click on 'Add owner'
6. Choose same Owner and different Type
7. Click 'Add'

**Expected behavior**
A new record for the same Owner with different Type is added

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Chrome
 - Version 101.0.4951.54

**Comment by maggiehays** [comment]
Hi @chriscollins3456, can you take a look at this one?

**Comment by jjoyce0510** [comment]
Hi @Vladislaff - thanks for reporting.

We intentionally implemented it this way, so that a single user has only a single type of ownership. Can you please help us to understand the use case for showing duplicate entries for a single user as an owner? 

I'd also recommend that we create a feature request for this, as it is part the well-understood, expected behavior of DataHub.

Thanks
John

**Comment by Vladislaff** [comment]
Hi @jjoyce0510. 

Sometimes one person can be in both roles - a Business owner and a Data steward.

We migrated to DataHub from our inhouse data governance tool and when importing ownership with api it let us set the same user for multiple roles.

**Comment by jjoyce0510** [comment]
Interesting - are you actively using these ownership types to specify what the user can do?

**Comment by jjoyce0510** [comment]
Going to close this ticket soon due to inactivity

**Comment by jjoyce0510** [comment]
Closing the ticket, we should definitely consider opening a feature request for this ask. cc @maggiehays
