### ISSUE TITLE
Copy URN" button in UI throws exception --Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')

### ISSUE THREAD

**Issue by YTQ419** [datahub-project/datahub#4921]
<img width="794" alt="exception" src="https://user-images.githubusercontent.com/71495889/168577518-ee950e9c-ac44-44c0-9f53-1e99a7dbb8eb.png">

**Comment by pedro93** [comment]
Hello @YTQ419 

Following up on John's request. Could you provide us some more details into your setup?
What version of DataHub are you working with?
How was it deployed?
How did you ingest metadata?
Is this a reproducible issue for any metadata or just for that hive table?

Thanks!

**Comment by YTQ419** [comment]
> Hi @YTQ419 - what browser are you working on and which version?

Chrome-version 101.0.4951.67

**Comment by YTQ419** [comment]
> Hi @jjoyce0510 

My browser is  Chrome-version 101.0.4951.67

**Comment by Masterchen09** [comment]
Hi all,

this issue is caused the unavailable Clickboard API, when the UI is served in an insecure context (not via HTTPS). This PR #4963 "fixes" this issue by hiding the buttons if the Clipboard API is not available.

For more information see here: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
