### ISSUE TITLE
How to set datahub-actions docker file using environment parameter

### ISSUE THREAD

**Issue by jeahyunkim** [datahub-project/datahub#4941]
**Describe the bug**
I started datahub-actions docker images using docker-compose environment parameter.

`KAFKA_BOOTSTRAP_SERVER`, `KAFKA_PROPERTIES_SECURITY_PROTOCOL` parameters were working.
but not working `KAFKA_PROPERTIES_SASL_MECHANISM`,  `KAFKA_PROPERTIES_SASL_JAAS_CONFIG`, `KAFKA_PROPERTIES_SASL_MECHANISM` parameters.

Also I set `SPRING_*` prefix kafka confing. but did not working.

```yaml
    - KAFKA_BOOTSTRAP_SERVER=brokers:9092
    - KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
    - KAFKA_PROPERTIES_SASL_MECHANISM=PLAIN
    - KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username=a password=a;
    - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
    - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=PLAIN
    - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username=a password=a;

``` 

**To Reproduce**

docker-compose.yaml datahub-actions services component run

```yaml
services:
  datahub-actions:
...
```

**Expected behavior**
datahub-actions component set kafka sasl config.

**Screenshots**

datahub-actions error logs.

```
%4|1652856460.649|FAIL|rdkafka#consumer-1| [thrd:broker:9092/bootstrap]: thrd:broker:9092/bootstrap: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 223ms in state UP, 4 identical error(s) suppressed)
```

**Additional context**

I read https://datahubproject.io/docs/how/kafka-config/ reference for kafka sasl config.
This reference guide to me how to configure kafka sasl config about datahub-frontend, gms, mce-consumer-job, mae-consumer-job...
But I can not find datahub-actions components kafka sasl config.

**Comment by jjoyce0510** [comment]
Hi @jeahyunkim. The problem here is that our datahub-actions container does not expose the environment variables for detailed Kafka Connection params. That being said, if you use a custom recipe by mounting your own Actions Config file (described [here](https://github.com/acryldata/datahub-actions)) into the container, you can customize the Kafka parameters in any way you want as described [here](https://datahubproject.io/docs/actions/sources/kafka-event-source#configure-the-event-source) --> simply use the "consumer_config" block to provide any custom kafka consumer params. 

I'm going to close this issue as there is a resolution as detailed above. Please reach out if you have additional questions, or raise an issue against the DataHub Actions repository (https://github.com/acryldata/datahub-actions) if there's an issue discovered. 

Thanks
John
