### ISSUE TITLE
Number of entities by Entity Type and by Platform do not match

### ISSUE THREAD

**Issue by devigeetha** [datahub-project/datahub#5172]
**Describe the bug**
in the homepage
under Explore your Metadata  Dataset as 48.2K
under Platforms
oracle as 24.8K,Greenplum as 24.6k Sqlserver as 1.1k
so the dataset entities count and platform counts are not matching

**To Reproduce**

**Comment by chriscollins3456** [comment]
@devigeetha can you check to ensure that containers (databases, schemas) in these platforms aren't making up for the diff?  We recently had someone else raise the same concern as here, but the numbers ended up adding up when considering all types of entities within your platform.

**Comment by jjoyce0510** [comment]
Hi @devigeetha ! 

This is because the Platform total count includes both Dataset (Tables) AND containers of Datasets like Databases, Schemas, etc, whereas the Datasets aggregate count includes only Datasets.

I'm interested to understand the implications of this for your company - is this a major painpoint?

I've gone ahead and created a Feature Request for this that folks can upvote and comment on publicly. Find it here -> https://feature-requests.datahubproject.io/p/breakdown-counts-by-entity-type-on-platform-cards-home-page

Going to go ahead and close the issue as "Won't Solve" (yet). 

John
