### ISSUE TITLE
Logout does not work when manually visiting logout route url

### ISSUE THREAD

**Issue by benmarte** [datahub-project/datahub#5690]
**Describe the bug**
Logout does nto work if you manually navigate to the logout URL `/logOut`

**To Reproduce**
1. Login to Datahu
2. In your browser type `https://demo.datahubproject.io/logOut` - Browser redirects you back to homepage
3. 2. In your browser type `https://demo.datahubproject.io/logOut/` - Returns a 404

**Expected behavior**
I expect the user to be logged out when visiting the logout url.

**Desktop (please complete the following information):**
 - OS: OSX Monterrey 12.4
 - Browser: Chrome
 - Version: Version 104.0.5112.101

**Comment by jjoyce0510** [comment]
Thanks for raising, and for the PR!

**Comment by jjoyce0510** [comment]
So I'm a bit concerned because hitting the /logOut endpoint does in fact do something on the server. It will hit the end_session endpoint for the IdP, which should revoke any Idp-minted browser state (cookies). 

![Screen Shot 2022-08-22 at 3 19 32 PM](https://user-images.githubusercontent.com/17549204/186028927-19dc0392-3bf7-4ff1-92a6-52e3cf91c3c5.png)

**Comment by jjoyce0510** [comment]
See CentralLogoutController.java - https://github.com/datahub-project/datahub/blob/master/datahub-frontend/app/controllers/CentralLogoutController.java#L40

**Comment by jjoyce0510** [comment]
Confirmed that we still need this call to localhost:9002/logOut!
