### ISSUE TITLE
mssqlserver cannot pull stored procedure'schema

### ISSUE THREAD

**Issue by sz-justinwang** [datahub-project/datahub#5987]
![image](https://user-images.githubusercontent.com/72057154/191146893-de14fb3d-6e8b-4149-9775-f9b00df4c53f.png)

**Additional context**

sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms:8080'
source:
    type: mssql
    config:
        platform_instance: mssql\test
        database: protestdb
        password: '${admin_Password}'
        host_port: 'mssqltest:1433'
        env: prod
        username: '${admin}'
pipeline_name: 'urn:li:dataHubIngestionSource:6577e870-5dce-4458-bfc0-5f6d9c939579'

**Comment by mayurinehate** [comment]
Hey @sz-justinwang , can you please add more details about observed and expected behaviour for this issue ?

**Comment by laulpogan** [comment]
Hi @sz-justinwang  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.
