### ISSUE TITLE
Generating Access Tokens Error

### ISSUE THREAD

**Issue by zcw5116** [datahub-project/datahub#6167]
document link： https://datahubproject.io/docs/api/graphql/token-management
datahub version: 0.8.45.2

When I execute the following command:

curl --location --request POST 'http://cloud:8080/api/graphql' \
--header 'X-DataHub-Actor: urn:li:corpuser:datahub' \
--header 'Content-Type: application/json' \
--data-raw '{ "query":"{ createAccessToken(input: { type: PERSONAL, actorUrn: \"urn:li:corpuser:datahub\", duration: ONE_HOUR, name: \"my personal token\" } ) { accessToken metadata { id name description} } }", "variables":{}}'

errors printed on the screen:

{"errors":[{"message":"Validation error (FieldUndefined@[createAccessToken]) : Field 'createAccessToken' in type 'Query' is undefined","locations":[{"line":1,"column":3}],"extensions":{"classification":"ValidationError"}}],"data":null,"extensions":{}}

**Comment by laulpogan** [comment]
Hi @zcw5116  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [slack.datahubproject.io](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.
