### ISSUE TITLE
bigquery lineage error makes job hung

### ISSUE THREAD

**Issue by ananbas** [datahub-project/datahub#6196]
**Describe the bug**
bigquery lineage error makes job hung because of super long sql query

**To Reproduce**
execute a super long SQL query and then trigger a bigquery lineage ingestion, then in the log there is an error during lineage extraction and then nothing happen. 

I need to cancel the job manually.

**Expected behavior**
lineage eror but job not hung, still continue to next records.

attached the logs below, in the logs we can see that the SQL query is truncated (not complete).
I dont know is this BQ limitation in the audit logs or it is in  the sql lineage extractor.

[exec-urn_li_dataHubExecutionRequest_f20bd39a-dccc-448b-a268-fb9bfe58b5c1.log](https://github.com/datahub-project/datahub/files/9778109/exec-urn_li_dataHubExecutionRequest_f20bd39a-dccc-448b-a268-fb9bfe58b5c1.log)

**Comment by treff7es** [comment]
@ananbas can you try using `bigquery-beta` instead of `bigquery` source?
It contains a bunch of bug fixes and hopefully there you won't see this issue.

**Comment by laulpogan** [comment]
Hi @ananbas  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [slack.datahubproject.io](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.
