### ISSUE TITLE
UI: Lineage edge glitch while moving node

### ISSUE THREAD

**Issue by ShaileshParmar11** [datahub-project/datahub#6199]
**Describe the bug**
The lineage edge is sticking at same place even if node is moving

**To Reproduce**
- go to lineage view [here](https://demo.datahubproject.io/dataset/urn:li:dataset:(urn:li:dataPlatform:snowflake,long_tail_companions.analytics.pet_details,PROD)/Lineage?filter_degree___false___EQUAL___0=1&is_lineage_mode=true&page=1&separate_siblings=false&show_columns=true&unionType=0)
- move node to any where

**Expected behavior**
Edge should move as well with node

**Screenshots**

https://user-images.githubusercontent.com/71748675/195661201-39d4d589-3a27-4e01-9409-86ebe4515b5a.mp4

**Desktop (please complete the following information):**

**Additional context**

**Comment by aditya-radhakrishnan** [comment]
Thanks for reporting this bug. @chriscollins3456 can you take a look and follow up here?

**Comment by chriscollins3456** [comment]
hey @ShaileshParmar11 ! I just merged a PR that should fix this issue right here: https://github.com/datahub-project/datahub/pull/6462

Once we confirm this problem is solved I'll close this issue, but please let us know if it's fixed for you once you either pull from head or upgrade your instance with our next release!

**Comment by chriscollins3456** [comment]
Looks like it's solved to me. Closing now.
