### ISSUE TITLE
Druid ingestion unable to get column information due to an error

### ISSUE THREAD

**Issue by vqcuong** [datahub-project/datahub#6239]
**Describe the bug**
I try to ingest druid to datahub but I couldn't do it successfully and got the error message at every datasource "unable to get column information due to an error -> This result object does not return rows. It has been closed automatically.". I've deploy my datahub on the server using docker and docker-compose. My recipe for ingestion (yaml) is below:
  source:
      type: druid
      config:
          username: druid_system
          password: {druid-system-password}
          profiling:
              enabled: false
          host_port: '{druid-broker-host}:8082'

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/35632030/196661514-8007b11a-0519-4892-a9f0-8f8dd08a4a97.png">

**Desktop (please complete the following information):**
 - OS: macOS monterey on M1 chip
 - Browser: google chrome
 - Version 0.9.0

**Additional context**

**Comment by laulpogan** [comment]
Hi @vqcuong   this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.
