### ISSUE TITLE
Connection refused: http://elasticsearch-master:9200/ on EKS

### ISSUE THREAD

**Issue by anon-account-123** [datahub-project/datahub#6327]
**Describe the bug**
Getting this error on EKS, private subnet. I've posted this in the troubleshooting channel of slack but nobody responded: 
```
2022/10/31 23:12:01 Problem with request: Get http://elasticsearch-master:9200/: dial tcp 10.100.139.159:9200: connect: connection refused. Sleeping 1s
2022/10/31 23:12:01 Timeout after 2m0s waiting on dependencies to become available: [http://elasticsearch-master:9200/]
Does anyone know what's causing it?
```
**To Reproduce**
1. Create an EKS cluster placed in a private subnet
2. Follow instructions on https://datahubproject.io/docs/deploy/kubernetes/ up to ```helm install prerequisites datahub/datahub-prerequisites```
3. kubectl get pods
```
elasticsearch-master-0                              0/1     Pending   0          35s
elasticsearch-master-1                              0/1     Pending   0          35s
elasticsearch-master-2                              0/1     Pending   0          35s
prerequisites-cp-schema-registry-6f4b5b894f-kn9fh   2/2     Running   0          35s
prerequisites-kafka-0                               0/1     Pending   0          35s
prerequisites-mysql-0                               0/1     Pending   0          35s
prerequisites-neo4j-community-0                     0/1     Pending   0          35s
prerequisites-zookeeper-0                           0/1     Pending   0          35s
```

**Expected behavior**
Supposed to install

**Desktop (please complete the following information):**
 - OS: AWS Linux (EC2)

**Comment by laulpogan** [comment]
Hi @anon-account-123  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs. I'm sorry you didn't get support when you posted- feel free to repost in slack!

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.
