### ISSUE TITLE
Poorly formatted table name, contains ['$'] when try to parse the job log contain Legacy SQL

### ISSUE THREAD

**Issue by pandegorga** [datahub-project/datahub#6373]
**Describe the bug**
I'm working on ingest BigQuery metadata into datahub. There is an issue when Datahub trying to get usage statistic from legacy SQL. 
Poorly formatted table name, contains ['$'] when try to parse the job log contain Legacy SQL.  Ex: `credit_risk_loans_dimension$__PARTITIONS_SUMMARY__`

*To Reproduce*
1. Having Legacy SQL job like [this](https://cloud.google.com/bigquery/docs/managing-partitioned-tables#getting_partition_metadata_using_meta-tables)
2. Ingest metadata from BQ with enable the `include_usage_statistics`

Expected behavior:
I expect datahub still able to parse the table name from the legacy sql job like above

**Comment by laulpogan** [comment]
Hi @pandegorga this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [slack.datahubproject.io](https://slack.datahubproject.io/) and we can troubleshoot there. For now, I'm going to close this issue.
