### ISSUE TITLE
Failed to start the app with the mock server 

### ISSUE THREAD

**Issue by DoraemonHC** [datahub-project/datahub#6533]
I want to start the app with the mock server without running the docker containers by executing yarn start:mock,but I failed.
Error: Unknown type "EntityPrivileges". Did you mean "Privileges"?

Unknown type "EntityPrivileges". Did you mean "Privileges"? 
![20221123213526](https://user-images.githubusercontent.com/49641242/203560138-67696dd6-1d54-4949-bdda-3874c00e614d.png)

**Comment by dryqiao** [comment]
same problem, how did you solve it ?

**Comment by gamboad** [comment]
> Hi @DoraemonHC this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.
> 
> If you're still having trouble, please join us at [https://slack.datahubproject.io/ and](https://slack.datahubproject.io/%C2%A0and) we can troubleshoot there. For now, I'm going to close this issue.

I had the same issue and it is not seem a troubleshooting issue, If you follow the instructions listed [here](https://datahubproject.io/docs/datahub-web-react/), particular the following optional step you get the reported error.

Optionally you could also start the app with the mock server without running the docker containers by executing yarn start:mock. See [here](https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/graphql-mock/fixtures/searchResult/userSearchResult.ts#L6) for available login users.

I managed to make it run by including some missing types into datahub-web-react/src/graphql-mock/schema.ts

`import { loader } from 'graphql.macro';

import gql from 'graphql-tag';
import { buildASTSchema } from 'graphql';

const linageSchema = loader('../../../datahub-graphql-core/src/main/resources/lineage.graphql');
const authSchema = loader('../../../datahub-graphql-core/src/main/resources/auth.graphql');
const entitySchema = loader('../../../datahub-graphql-core/src/main/resources/entity.graphql');
const searchSchema = loader('../../../datahub-graphql-core/src/main/resources/search.graphql');

const recommendationSchema = loader('../../../datahub-graphql-core/src/main/resources/recommendation.graphql');
const appSchema = loader('../../../datahub-graphql-core/src/main/resources/app.graphql');

const graphQLSchemaAST = gql`
    ${recommendationSchema}
    ${appSchema}
    ${linageSchema}
    ${authSchema}
    ${entitySchema}
    ${searchSchema}
`;

export const graphQLSchema = buildASTSchema(graphQLSchemaAST);
`

However, the site does not render anything because the mockdata returns empty objects. It is still unclear what the purpose of this mode is and how to use it, the versioned code also seems to be incomplete.

**Comment by lyp000119** [comment]
hello,
If you just want to try or modify the front-end page, but `yarn start:mock` fails to start, you can change it like this, using the interface of the test environment

Form  datahub-web-react/src/setupProxy.js
```tsx
const logInFilter = function (pathname, req) {
     return pathname.match('^/logIn') && req.method === 'POST';
};

if (process.env.REACT_APP_MOCK === 'true' || process.env.REACT_APP_MOCK === 'cy') {
     // no proxy needed, MirageJS will intercept all http requests
     module. exports = function () {};
} else {
     // create a proxy to the graphql server running in docker container
     const { createProxyMiddleware } = require('http-proxy-middleware');

     module. exports = function (app) {
         app. use(
             '/logIn',
             createProxyMiddleware(logInFilter, {
                 target: 'https://demo.datahubproject.io',
                 changeOrigin: true,
             }),
         );
         app. use(
             '/authenticate',
             createProxyMiddleware({
                 target: 'https://demo.datahubproject.io',
                 changeOrigin: true,
             }),
         );
         app. use(
             '/api/v2/graphql',
             createProxyMiddleware({
                 target: 'https://demo.datahubproject.io',
                 changeOrigin: true,
             }),
         );
     };
}
```
