### ISSUE TITLE
Why I can't see more details like Min, Max and Median of my column?

### ISSUE THREAD

**Issue by md2netamanda** [datahub-project/datahub#6656]
Hello everyone, 
I am new in Datahub. Actually, I just created a server because we are checking its applicability in our company. Now I am discovering a postgres database. At this moment we created a connection with only one table just to be quick. The discovery works fine, but in the Stats aba some information are empty like Min, Max and Median. Could someone tell me why, and how to solve this issue?
Regards, Amanda Lima

**Comment by laulpogan** [comment]
Hi @md2netamanda this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io/) and we can troubleshoot there. For now, I'm going to close this issue.
