### ISSUE TITLE
Cannot load Business Glossary on local development

### ISSUE THREAD

**Issue by Weixian13** [datahub-project/datahub#6668]
Run GMS with local cannot load the Business Glossary. The Business Glossary has been created successfully. When Run the GMS withDocker, the Business Glossary can be loaded normally.

 - MacOS
 - chrome
 - Version 0.9.3

**Comment by laulpogan** [comment]
Hi @Weixian13 could you provide logs/recipes? You may not have the glossary in the database that local GMS connects with, or the correct user permissions to view in the UI!

**Comment by laulpogan** [comment]
Hi @Weixian13  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.
