### ISSUE TITLE
Can't build datahub-frontend-react docker image

### ISSUE THREAD

**Issue by jkl0898** [datahub-project/datahub#6669]
**Describe the bug**

Use command: 
docker-compose build datahub-frontend-react 

to build docker image

**To Reproduce**
Use command: 
docker-compose build datahub-frontend-react 

to build image, but failed.

datahub source version: tag v0.9.1

error msg:
failed to solve: executor failed running [/bin/sh -c apk --no-cache --update-cache --available upgrade     && apk --no-cache add perl openjdk8 openjdk11]: exit code: 1

#0 3139.3 ERROR: Failed to create usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar: Connection aborted
#0 3139.3 ERROR: openjdk8-jre-lib-8.302.08-r1: BAD signature

**Expected behavior**
build docker image successfully.

**Screenshots**
failed to solve: executor failed running [/bin/sh -c apk --no-cache --update-cache --available upgrade     && apk --no-cache add perl openjdk8 openjdk11]: exit code: 1

#0 3139.3 ERROR: Failed to create usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar: Connection aborted
#0 3139.3 ERROR: openjdk8-jre-lib-8.302.08-r1: BAD signature

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser: chrome
 - Version v0.9.1

**Additional context**

**Comment by laulpogan** [comment]
Hi @jkl0898 , this seems like an issue with local build and your environment, rather than a DataHub bug. This docs page could be helpful for resolution: [https://datahubproject.io/docs/docker/development](https://datahubproject.io/docs/docker/development). It also seems that your version 0.9.1 is out of date with the current release, 0.9.3.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io/) and we can troubleshoot there in #getting-started or #troubleshoot. For now, I'm going to close this issue.

**Comment by jkl0898** [comment]
> Hi @jkl0898 , this seems like an issue with local build and your environment, rather than a DataHub bug. This docs page could be helpful for resolution: https://datahubproject.io/docs/docker/development. It also seems that your version 0.9.1 is out of date with the current release, 0.9.3.
> 
> If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)]([https://slack.datahubproject.io/) and](https://slack.datahubproject.io/)%C2%A0and) we can troubleshoot there in #getting-started or #troubleshoot. For now, I'm going to close this issue.

thanks!
