### ISSUE TITLE
There is difference between ingestion run by schedule and manual run 

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#6860]
**Describe the bug**
There is two runs and two with different result. one successful... second no. Scheduled ingestion runs with errors and fall. but manual run of this ingestion goes to successful end.

**To Reproduce**
1. Go to ingestion at the morning. and see ingestion runs with errors 
2. Click on manual run and see the succesfunl results.
3. Scroll down to other ingestion and was "Running..." - if the few ingestions setups right at the same time it could be frozen till morning or forever.

**Expected behavior**
Run scheduled ingestion as manual runs. avoid same time runs to avoid frozen ingestion at "Running" status which never ends.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Probably there are could be two bugs. first with ingestion runs. second with a schedule runs at same time. 

Attached files first runs by schedule. second runs manually. 

[schedule-exec-urn_li_dataHubExecutionRequest_1b864792-565f-4c15-b0d3-e1b0f823f74b.log](https://github.com/datahub-project/datahub/files/10306994/schedule-exec-urn_li_dataHubExecutionRequest_1b864792-565f-4c15-b0d3-e1b0f823f74b.log)
[manual-exec-urn_li_dataHubExecutionRequest_b67b386f-d7da-45c2-ac7b-d2f6e06cf42b.log](https://github.com/datahub-project/datahub/files/10306995/manual-exec-urn_li_dataHubExecutionRequest_b67b386f-d7da-45c2-ac7b-d2f6e06cf42b.log)

**Comment by YuriyGavrilov** [comment]
![image](https://user-images.githubusercontent.com/44679014/209638415-c5414131-afd6-42fe-8cac-e100e78ff722.png)

**Comment by YuriyGavrilov** [comment]
ingestion YAML:
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms-datahub-gms:8080'
        token: '${ingestions_by_yua}'
source:
    type: kafka
    config:
        connection:
            consumer_config:
                security.protocol: SSL
                ssl.keystore.password: '${datacatalog_cert_key}'
                ssl.keystore.location: /opt/certs/ns-cert/pkcs12.crt
            bootstrap: 'bootstrap.kaas1pss25.epaas.s7.aero:9093'
            schema_registry_url: 'https://ksr-eip-m1.s7.aero'
        env: PROD
        platform_instance: Kafka.Pss
pipeline_name: 'urn:li:dataHubIngestionSource:719290ee-ebe2-47fd-9686-de37a0f1d814'
transformers:
    -
        type: simple_add_dataset_tags
        config:
            tag_urns:
                - 'urn:li:tag:product.PSS'
    -
        type: simple_add_dataset_ownership
        config:
            owner_urns:
                - 'urn:li:corpuser:m.filippov'
            ownership_type: PRODUCER
    -
        type: simple_add_dataset_domain
        config:
            domains:
                - 'urn:li:domain:1c86cb03-d74b-4cbb-b502-f0550f54b15d'

**Comment by jjoyce0510** [comment]
Hi there! 

For now, you can cancel the two tasks that are in the running state. In my opinion, your `datahub-actions` pod, which runs these ingestions, was overwhelmed and probably needs higher resource allocation limits (CPU and memory). To do this, you can change the values.yaml file to increase the resources of the `datahub-actions` pods. Alternatively, you can stagger your ingestion schedule so that heavy ingestion does not run at the same exact time.

In terms of the Scheduled Ingestion run failing, when the Manual Run succeeds: It's like the same issue (resource competition). Can you please share the logs of the failing scheduled run? It's possible for a variety of reasons that a scheduled run fails at time T1 and then a Manual run succeeds at time T2. Under the hood, these 2 processes share the exact same code pathway so there should be no consistent differences in the results. 

Please reach out on Slack to discuss further. Closing the ticket due to answer!

Cheers
John
