### ISSUE TITLE
good to be able to disable the "never expired" tokens option due to security reason

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#6861]
**Describe the bug**
good to be able to disable the "never expired" tokens option due to security reason

**To Reproduce**
1. Go to settings
2. Click on 'Access tokens'
3. Scroll down to 'Expires in'
4. will be as option 'never expires'

**Expected behavior**
there should not be "never expired" option or it should be disabled as an option.

**Screenshots**
![image](https://user-images.githubusercontent.com/44679014/209650672-d3332002-8a60-4db7-a063-991871d75af0.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by jjoyce0510** [comment]
We originally did not have a 'Never' expired token type. However, we received a lot of pushback for the community. In fact, many folks wanted to generate Never expiring tokens for their automated ingestion jobs although we had communicated the risks of doing so. For that reason, we decided to introduce support for it back in with a warning indicator (red text).

For now, we do not intend to backtrack on this decision, at least until we have an alternative option available for non-expiring tokens. Hope this helps to clarify. Closing this ticket due to answer provided.

Cheers
John
