### ISSUE TITLE
Soft deleted entity ML Model still appears in the UI (reopened)

### ISSUE THREAD

**Issue by jazzblue** [datahub-project/datahub#7120]
This issue was closed incorrectly, please see:
https://github.com/datahub-project/datahub/issues/6328

The meaning of soft delete is that it can be restored, but while it is in soft deleted state it is deleted as far as any user whether API or UI. The soft deleted entity should not appear in the UI. This is a real problem and should be fixed.
I am reopening it here.

**Comment by aditya-radhakrishnan** [comment]
Hey @jazzblue sorry if we closed that issue before you felt it was resolved.

The DataHub Core Team has decided that yes, soft deletion, means it can be restored, but we have implemented it so that soft deletion means the entity _can_ appear in the UI. It will not be discoverable via Search or other mechanisms though.

If you would like something to not appear in the UI and you have no need for that metadata anymore, I would recommend you hard delete.

Hope that makes things clear. Thank you for engaging in the community!
