### ISSUE TITLE
Minor: User Profile Image can have colored background 

### ISSUE THREAD

**Issue by jjoyce0510** [datahub-project/datahub#7145]
**Describe the bug**

Based on this Slack thread: https://datahubspace.slack.com/archives/CV2UXSE9L/p1674716341745369

When a user uploads a profile image with a transparent background, we will see the underlying default color behind the image. 
This is a minor issue but a great first issue.

**Comment by sethppierce** [comment]
Hello! I'd like to work on this bug, but I don't have access to that slack thread? Is there anyway I could get more information about it?

**Comment by hieunt-itfoss** [comment]
@sethppierce More detail below:
**Describe the bug**
If the users use a picture with a **transparent background** for their profile, the background is filled up with the default color.

Example: 
https://github.com/bossenti.png

**Expected behavior**
- User profile displays correctly without background color.

**Actually**
[Attached picture](https://files.slack.com/files-pri/TUMKD5EGJ-F04LEHBD422/bildschirm__foto_2023-01-26_um_07.54.24.png)

**Comment by bossenti** [comment]
>  please leave a comment with the version that you tested it with.

The bug still appears in DataHub `0.10.0` as reported
