### ISSUE TITLE
Text container for column description is broken when filtering columns using schema search

### ISSUE THREAD

**Issue by srinify** [datahub-project/datahub#7528]
**Describe the bug**
When using schema search in the Dataset view, column description disappears to the user.

**To Reproduce**

1. Add a column description using Markdown that's lengthy (and resembles screenshot below)
2. Use schema search to filter columns to just this column
3. Observe description section disappear (hidden scroll box)

**Expected behavior**

Container for dataset description is maintained / matches the user experience before schema search is applied

**Screenshots**
1. Dataset Description before using schema search

![dh1](https://user-images.githubusercontent.com/801507/224027409-a6d19488-f171-4e47-bd0d-9a5ea51c8e5b.png)

4. Description after using schema search

![dh2](https://user-images.githubusercontent.com/801507/224027490-54c0dd8b-5ca8-4c00-bcbd-2fa1074ed472.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser All browsers (Brave, Chrome, Safari)
 - Version 0.10

**Additional context**

Maggie & Aditya confirmed that this is indeed a bug: https://datahubspace.slack.com/archives/CV2UXSE9L/p1678317382698979

**Comment by jfrancos-mai** [comment]
To clarify re: the behavior being different based on scrolling to the variable vs finding it through search:

The issue was that “read more” wasn’t triggering a change in table height – so if there were only a couple variables and the height of the table was relatively small, this bug would show itself even without doing a schema search.
