### ISSUE TITLE
SSO users not showing up in Users & Groups

### ISSUE THREAD

**Issue by TheStanHo** [datahub-project/datahub#8601]
**Describe the bug**
Some users who are SSO'ing into datahub, are not showing in the list of Users in the "Manage Users and Groups" Screen.
Some users can be seen but not all users that have logged in via SSO can be seen in the users and groups

**To Reproduce**
1. Go to datahub frontend 
2. Sign in via Microsoft SSO
3. Go to settings -> Users & Groups
4. User who signed in, doesn't show up in the list of Users

**Expected behavior**
All users to be shown in the list of Users

**Screenshots**
N/A

**Desktop (please complete the following information):**

 - Version [e.g. 0.10.5]

**Additional context**
In the datahub-frontend.debug.log i can see for some users 
it says DEBUG auth.sso.oidc.oidcCallbackLogic - User urn:li:corpuser:XXX@XXX.org already exists. Skipping provisioning

But there are no obvious errors or warnings thrown in the log

**Comment by mkih** [comment]
Also encountering this issue. Might be related to this issue: https://github.com/datahub-project/datahub/issues/3615

Tried deleting the users that supposedly already exist through both APIs and CLI but neither seem to have solved the problem. I suspect Microsoft SSO may occasionally change the user email lettercases which is the cause, but this is just a hunch..

**Comment by TheStanHo** [comment]
@mkih Yeah I also tried deleting it via the GraphQL and no luck there. 

I did notice however for users that did and did not appear in the UI that if you query the Postgres DB looking for aspect that contains "corpUser" that they appear there.

Users that appear in the UI only have 4 entries where as users that don't appear in the UI appear to have more than the 4 entries. When I delete 1 user via the UI as they appear there. The entries related to them in Postgres are also deleted. So maybe something to do with Postgres entries I'm assuming 🤷‍♂️

**Comment by JulienKleinmann** [comment]
Hello @mkih @TheStanHo, 
I ha the same issue on my installation. I spent a day trying to analyse logs and different user in the DB + trying to delete/add user manually before signing in via sso (using sql and a mix of all api ). 
In the end I remembered that I had deactivated neo4J in order to use Elasticsearch for the graph DB (I am installing in kubernetes).  
**After re enabling neo4J it worked for new users, old ones I had to supress them via graphapi and then on the next login it works.** 
Not sure what the issue is but I would believe the front end is unable to correctly use elastic for graphDB. 
Hope this help. 
Kind regards,
