### ISSUE TITLE
Inconsistent policy resource filter enum field

### ISSUE THREAD

**Issue by skrydal** [datahub-project/datahub#9085]
**Describe the bug**
Policies with either `urn` or `resource type` resource filter don't work properly with current `master`.

**To Reproduce**
1. Go to permissions view
2. Create new policy with either `urn` or `resource type` filter (i.e. one applied only to datasets)
3. Try to perform allowed action (make sure user performing action **is not granted privilege to perform it through any other policy but the one created in step 2**

**Expected behavior**
User is allowed to perform the action thanks to newly created policy.

**What actually happens**
User is not allowed to perform the action. Moreover I can see line in GMS logs (this one in particular if policy defines `resource type`:
```
ERROR c.datahub.authorization.PolicyEngine:217 - Unsupported field type RESOURCE_TYPE
```
Moreover UI policy detail view does not show Resource Types/Urns correctly (shows `All` instead).

**Analysis and impact**
The problem appears likely due to this change:
https://github.com/datahub-project/datahub/pull/8846/files#diff-58b6f3004a3b455a942ba12668b065ba8e19ea6be368f1806490d2ebfd564868L10
which now became:
https://github.com/datahub-project/datahub/pull/8846/files#diff-4d637a551329664ce27ddbbffe2ea1566e42937057aee439abdfb8e712753e22R10

This causes any policies with `urn` or `resource type` resource filter to not work properly and producing the ERROR log mentioned above. **This problem affects both policies existing at the time of upgrade and any newly created via UI**.
Fixing the problem in UI seems to be quite straight-forward but to change existing aspects in relational database will require some custom upgrade logic.

**Temporary work-around**
Policies can be updated manually via `datahub put` command sending `dataHubPolicyInfo` aspect with filter looking like:
```
   "resources": {
     "filter": {
       "criteria": [
         {
           "field": "TYPE",
           "condition": "EQUALS",
           "values": [
             "dataset"
           ]
         }
       ]
     }
```
instead of
```
   "resources": {
     "filter": {
       "criteria": [
         {
           "field": "RESOURCE_TYPE",
           "condition": "EQUALS",
           "values": [
             "dataset"
           ]
         }
       ]
     }
```

**Comment by pedro93** [comment]
Thank you for opening this ticket @skrydal, I am in the process of creating a fix for this!

**Comment by skrydal** [comment]
Hi @pedro93 
Thank you for notifying me. I have already created a PR fixing UI:
https://github.com/datahub-project/datahub/pull/9087
Weren't sure where to add custom upgrade logic fixing existing aspects.

**Comment by pedro93** [comment]
Will look at the PR, thanks for the contribution!
Regarding upgrade logic. Since the PR that broke this wasn't released in a previous version of DataHub, it means that the folks affected by this are the ones running DataHub on non-released, bleeding-edge docker tags like `head`. 
This is ok I think for quickstart use-cases where folks can just reset their databases. 
For other cases I think having a release note about this with your work-around is sufficient. 

What do you think?

**Comment by skrydal** [comment]
Thank you for quick review and merge of the changes. I created PR with docs change here:
https://github.com/datahub-project/datahub/pull/9093
As I applied the change manually myself in my environments, it is fine with me. Although I thought there would be some automated mechanism in place updating aspects for which schema changed (obviously requiring custom logic for each case). Is there such thing available in the datahub, in general?

**Comment by pedro93** [comment]
`Although I thought there would be some automated mechanism in place updating aspects for which schema changed`
We have the [upgrade jobs (old version)](https://github.com/datahub-project/datahub/tree/master/datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/nocodecleanup) or [system update job (new version)](https://github.com/datahub-project/datahub/tree/master/datahub-upgrade/src/main/java/com/linkedin/datahub/upgrade/system) which right now only performs ES migrations but since this is a bug that wasn't released on a stable version, we won't be creating such a job this time around.

**Comment by pedro93** [comment]
FYI I'm going to add support for both policy schemas in the code which will remove the need for an update process.
