### ISSUE TITLE
How to solve the question?

### ISSUE THREAD

**Issue by Joe-2002** [datahub-project/datahub#9333]
在南京开源活动中了解到datahub，可以使用向量检索+知识图谱检索，能够去除无效信息，我们想通过refs提供的信息使用生成大模型来回答query的问题，不知道是否可以使用datahub，来先对refs完成检索。之前有使用过向量检索，效果不佳。
需求：
给定一个用户搜索问题query，多条搜索结果摘要，利用生成模型组织搜索引擎返回的多条检索结果，生成一个正确、丰富、语义通顺、完全满足用户需求的答案。
case：
{"query": "水王子娶了谁", "refs": ["1.水王子最终娶王默 。水王子名字叫水清漓,她是灵犀阁圣级仙子,都是盐的精灵王子,一直居住在水玲珑宫中,容貌精美,衣着绮丽,上面是水流纹样和宝蓝色夹克外套,下面是暗蓝色七分裤 。水王子高雅冷淡,不问世事,拥有很多法术,认为水的力量,由于水能量是非常强大的,因此没有人敢惹他 。水王子最在意的人是王默,为了让王默可以在水下拥抱自然,就把自己的上千年力量给了她,由此可见水王子是真心喜欢王默 。 2.水王子娶王默 。听说在《精灵梦叶罗丽》番外中水王子娶成年后的王默,在番外里边,王默早已出峻工了一个大美女,到能够结婚的年龄,她穿着洁白婚纱拿着一束手捧花,嫁给水王子,宣传海报界面十分唯美意境 。当时“水默”那对CP一出场就奔网友们锁死了,王默在净化水湖内看到水王子的那一刻就对水王子一见钟情了,而水王子也很爱王默,为救王默甘愿和自己的妹妹冰公主为敌,王默抽到了噩梦手术后,水王子将她唤起,两个人最终走到一起,迈入圆满的结局 。", "很多人都猜测王默的可能性最大,毕竟水王子唯一动心的女孩就是王默了,但其实两人很大可能无法在一起。 王默是大家最愿意见到和水王子结婚的人。这么多集过去了,王默是唯一一个让水王子心动的女孩,水王子对其他人都是十分的高冷,对一些事情也都不是很在意,但只要是王默的事情那么一定就会十分留意,并且还愿意为了王默来到人间,也好几次不顾危险救了王默,可以看出水王子是真的喜欢王默的。而王默也对水王子不反感,对水王子很感激。但是两人在一起可能性不大,最大的原因就是因为一个是人类,一个是仙,两人寿命相差太大,王默只有短短几十年,而水王子却有很长的寿命,人和仙在一起概率太低了。 那么王默和水王子在一起的概率这么低,水王子最后到底会选择谁了?有些粉丝认为水王子很可能会和灵公主在一起,这是为什么了?因为大家都觉得王默和灵公主在有些方面十分相似,比如都十分的温柔,看来水王子也喜欢温柔的女生。另外灵公主也是仙子,这样的话就不用担心两人的寿命不一样了,因此很多人都认为灵公主和水王子在一起的概率是最大的。", "《精灵梦叶罗丽》中水王子最后娶了王默。", "水王子最后娶了王默。"], "answer": "截止到2023年6月，关于动漫《精灵梦叶罗丽》中的水王子娶了谁的问题，并没有官方答案。根据网传说法，水王子娶了王默，因为《精灵梦叶罗丽》番外的宣传海报界面是王默穿着洁白婚纱拿着一束手捧花，好像是要嫁给水王子。\n\n王默是唯一一个让水王子心动的女孩，水王子对其他人都是十分的高冷，对一些事情也都不是很在意，但只要是王默的事情那么一定就会十分留意，并且还愿意为了王默来到人间，也好几次不顾危险救了王默，可以看出水王子是真的喜欢王默的。而王默也对水王子不反感，对水王子很感激。"}
{"query": "马云女儿", "refs": ["而马云的女儿马雪则一直被保护得非常好,外界少有对马雪的报道,只有一张马雪19岁的照片,图中的马雪与马云眉眼非常相近", "但是马云的儿女能够说是中国最低调的富二代了,据公开材料显现,马云的儿子叫马元坤,理想生活中是一个十分凶猛的学霸,但关于马元坤的长相很多人都没见过,不过马云的做法也对,毕竟如今的网络很复杂,马云只想让本人的儿子好好生活,不想被太多人关注也是理所应当的。 马云的女儿叫马雪,比马元坤愈加低调,马雪的长相很清纯娟秀,是一个阳光的小姑娘,今年19岁了,当马雪的照片流显露后,不少网友表示:缺女婿吗?置信今后马云的这对儿女肯定会分发出本人的光辉,对此你们怎样看呢?", "马云有一个女儿,名叫马雪。马雪的外貌在很大程度上也是从马云那里继承的。 许多网民看到了最近一张马雪20岁的照片,并声称马云的女性版已经上线了! 虽然马云不太好看,但他的女儿仍然很年轻可爱。", "马云的女儿叫“马元坤”,这个名字听起来非常霸气,而且寓意也很好,不过马云的女儿并不是普通人,她是一个美国人,名字叫“马晓晴”。马晓晴从小就学习芭蕾舞,长大后还考上了美国哈佛大学,可以说是妥妥的白富美。”马云的女儿是不是很漂亮呢?其实马云的女儿还有一个妹妹,她的颜值也是非常高的,看起来和马云一样,都是高鼻梁大眼睛,而且还有一双迷人的大长腿,真的是让人羡慕不已。 近日,李连杰与19岁的大女儿jane的一组照片曝光,照片中二人一同现身颁奖礼,李连杰身穿黑色休闲服,头戴黑色鸭舌帽,戴黑框眼镜,大女儿jane则身穿粉色西装外套,内搭白色衬衫,气质落落大方,全程陪在父亲身边,与他人热情交谈。 据悉,此次活动是马云组织一些商业精英发起的,能够邀请到李连杰更是让活动备受关注。在现场的照片中可以看到马云和李连杰以及李连杰大女儿坐在了一个餐桌,马云也是与李连杰亲切交谈,女儿jane则是满脸崇拜的在一旁注视着马云叔叔,宛如一个小迷妹。 此次也并不是李连杰带女儿首次出席这样的活动了,在与他人的合照中,19的jane也表现的十分自信得体,丝毫没有怯场,尽显职场女强人的风范。而李连杰也有意带女儿认识更多商界成功人士,为他今后的铺路。 jane是李连杰与智利的大女儿,她从小就一直是个学霸,李连杰也对女儿的教育观念十分开明,希望她可以自我独立,尊重她自己的意愿,jane也非常争气,现在已经是哈佛大学的高材生。 jane前不久还在自己社交平台上官宣了自己参加巴黎名媛舞会的消息,试装照片曝光后也受到了网友的关注,她身穿抹胸蓝裙露出好身材,在消息发布后的采访中,她也表示自己作为李连杰的女儿,身份特殊,就应该承担起更多的责任,多为公益事业做贡献。 而李连杰这些年也一直从事公益事业,不仅每年都捐款,还把自己的基金会打理的有模有样,同时也尽自己所能帮助需要的人,为女儿从事公益事业树立了榜样!"], "answer": "据网传消息，马云的女儿叫马雪。\n\n马雪比马元坤愈加低调，马雪的长相很清纯娟秀，是一个阳光的小姑娘。马云的女儿马雪一直被保护得非常好，外界少有对马雪的报道，只有一张马雪19岁的照片，照片中的马雪与马云眉眼非常相近。"}
{"query": "肖战体重", "refs": ["肖战,体重:58kg,身高:183cm。 拥有一个正常的体重范围:完美的体重指数(BMI)=体重(公斤)/身高2(公尺2)。 标准体重的计算方法:身高-110=标准体重(公斤)所以你的标准体重是:176-110=66公斤。", "身高:183cm 体重:58kg", "网友透露肖战现在体重在130斤,意思是65公斤,作为身高183厘米的人来说,65公斤是不是太瘦了,他以前刚出道的时候有150斤,意思是75公斤,这个时候的肖战看起来脸颊还有点肉,现在完全是凹进去的,但棱角分明。 这个时候的肖战看起来脸上有点肉,作为183厘米的身高75公斤其实并不很胖,但网友们认为上镜看起来还是没有瘦下来帅,不瘦的时候看着眼神没有那种放电的感觉,瘦身之后,整个精气神像变了一个人,其实《陈情令》看起来已经很瘦,镜头上如此,私底下真的应该很瘦了。 按照肖战183厘米的身高计算,标准体重应该是72.1公斤,当时参加比赛的时候体重75公斤,的确有点超标了,但现在才65公斤,低于标准体重7公斤,折成14斤,说明肖战甩肉14斤,这个也是很厉害,其实男明星体重没有女明星的自我要求那么狠,但男明星的粉丝比女明星多,所以更看重自己的体重。", "肖战体重是58千克。", "肖战，1991年10月5日出生于重庆市，中国内地男演员、歌手。\n代表作品有《陈情令》《王牌部队》《余生，请多指教》《斗罗大陆》《梦中的那片海》"], "answer": "关于肖战体重，没有官方回答。据网传消息，肖战的身高为183cm，体重为58kg。\n\n肖战，1991年10月5日出生于重庆市，中国内地男演员、歌手。其代表作品有《陈情令》《王牌部队》《余生，请多指教》《斗罗大陆》《梦中的那片海》等。"}

**Comment by jakobhanna** [comment]
Why? Translated:



In the Nanjing open source activities learned datahub, you can use vector retrieval + knowledge graph retrieval, able to remove invalid information, we would like to use the information provided by the refs to generate a large model to answer the query, do not know if you can use datahub, to complete the retrieval of refs first. Have used vector retrieval before with poor results.
Requirement:
Given a user search question query with multiple search result summaries, use a generative model to organize the multiple search results returned by a search engine to generate an answer that is correct, rich, semantically fluent, and fully satisfies the user's needs.
case:
{"query": "who did the water prince marry", "refs": ["1. The water prince eventually married Wang Mo . The water prince name is water Qing Li, she is the spiritual rhinoceros pavilion saint level fairy, are salt of the elf prince, has been living in the water Linglong Palace, looks exquisite, dress beautiful, above is the water flow pattern and treasure blue jacket coat, below is the dark blue seven-minute pants . The Water Prince is elegant, cold and uninvolved in the world. He has many spells and believes in the power of water, and no one dares to mess with him because the water energy is very powerful. The most important person he cares about is Wang Mo. In order to let Wang Mo embrace the nature underwater, he gave her his thousands of years of power, which shows that the Water Prince really likes Wang Mo. 2. The water prince married Wang Mo. I heard in the "elf dream Yeloli" extra water prince married adult Wang Mo, in the extra side, Wang Mo has been out of Jun Gong a big beauty, to be able to get married age, she wore a white wedding dress holding a bouquet of hand bouquet, married to the water prince, the publicity poster interface is very beautiful mood. At that time, "water silent" that CP a pair of appearance on the run netizens lock, Wang Mo in the purification of water within the lake to see the water prince of the moment on the water prince love at first sight, and the water prince is also very much in love with Wang Mo, in order to save the Wang Mo is willing to and their own sister Ice Princess as the enemy, Wang Mo drew a nightmare surgery, the water prince will be her evocation of the two people finally come together! The two finally came together, moving towards a happy ending." , "Many people have guessed that Wang Mo's possibility is the greatest, after all, the only water prince heart girl is Wang Mo, but in fact the two are very likely to be unable to be together. Wang Mo is the person that everyone would love to see married to Prince Shui. So many episodes in the past, Wang Mo is the only one to let the water prince heart girl, water prince to other people are very high cold, to some things are not very concerned, but as long as it is the things of Wang Mo then will be very attention, and also willing to come to the earth for the Wang Mo, and several times in spite of the danger to save the Wang Mo, you can see that the prince of the water is really like the Wang Mo. And Wang Mo is not averse to the water prince, the water prince is very grateful. But the two together is unlikely, the biggest reason is because one is human, one is immortal, the two life expectancy difference is too big, Wang Mo only a few decades, while the water prince has a very long life expectancy, the probability of human and immortal together is too low. So the probability of Wang Mo and the water prince together is so low, the water prince in the end who will choose? Some fans think that the Water Prince will probably be with Princess Ling, why is that? Because we all feel that Wang Mo and the spirit of the princess in some aspects are very similar, for example, are very gentle, it seems that the water prince also like gentle girls. In addition, Princess Spirit is also a fairy, in which case there is no need to worry about the two people's lifespan is not the same, so many people think that Princess Spirit and Prince Water together is the greatest probability." , "Prince Water ended up marrying Wang Mo in Pixie Dream Yeloli." , "The Water Prince ends up marrying Wang Mo."] , "answer": "As of June 2023, there is no official answer to the question of who the Water Prince from the anime Pixiemon Yaroli married. According to netizen legend, Prince Water married Wang Mo, as the promotional poster interface for the "Pixie Dream Yeloli" extras shows Wang Mo wearing a white wedding dress holding a bouquet of hand bouquets, as if she is marrying Prince Water. \n\n Wang Mo is the only one to let the water prince heart girl, water prince to other people are very high cold, to some things are not very care, but as long as it is the things of Wang Mo then must be very attention, and also willing to come to earth for Wang Mo, and also a few times in spite of the danger to save the Wang Mo, you can see that the water prince is really like the Wang Mo. And Wang Mo also does not resent the Water Prince, and is very grateful to the Water Prince."}
{"query": "Ma Yun's daughter", "refs":["And Ma Yun's daughter Ma Xue has been very well protected, the outside world has little to Ma Xue's report, only a Ma Xue 19-year-old photo, the picture of Ma Xue and Ma Yun's eyebrows are very similar", "But Ma Yun's children can be said to be the most low-profile of the rich second-generation in China, according to the public 
> ...
