### ISSUE TITLE
can't build sources

### ISSUE THREAD

**Issue by ramansmirnou** [datahub-project/datahub#9804]
**Describe the bug**
Trying to follow dev tutorial - https://datahubproject.io/docs/developers/

**To Reproduce**
1. git clone https://github.com/datahub-project/datahub
2. cd datahub
3. ./gradlew build
4. Error:

> Task :buildSrc:compileJava FAILED
H:\datacatalog\buildSrc\src\main\java\io\datahubproject\OpenApiEntities.java:11: error: package com.linkedin.metadata.models.registry.config does not exist
import com.linkedin.metadata.models.registry.config.Entities;

**Expected behavior**
Code compiled, auto-generated and so on, no any errors

**Desktop (please complete the following information):**
 - windows 10

**Comment by ramansmirnou** [comment]
I checkout old version (v0.9.6) and seems it work as expected - it load dependencies for last hour. After import will be finished, will checkout not so old version.

**Comment by ramansmirnou** [comment]
yes, it work under linux

**Comment by does-not-matter-0** [comment]
I got the same error on Linux environment. 
```
> Task :buildSrc:compileJava
buildSrc/src/main/java/io/datahubproject/OpenApiEntities.java:9: error: package com.linkedin.metadata.models.registry.config does not exist
import com.linkedin.metadata.models.registry.config.Entities;
```

**Comment by ahringer** [comment]
I think it may be due to windows not handling symlinks correctly, as they are using in the setup of this project. there is a git config item to handle this I think.

**Comment by limike19870910** [comment]
I have done it. it's because you are using windows to develop the project, and buildSrc has two symbolic link which is treated as empty files. these two are "entity-registry/src/main/java/com/linkedin/metadata/aspect/plugins/config" and "entity-registry/src/main/java/com/linkedin/metadata/models/registry/config". Here is the solution :

the [Developer Mode](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development) has to be enabled first. Then the following commands can be used to enable  "symbolic links in Git" and recreating the symbolic links:

use powershell:
# enable core.symlinks config
git config --global core.symlinks true

# check the current core.sysmlinks config and scope
git config --show-scope --show-origin core.symlinks

# in case the core.sysmlinks config is still set locally to false, remove the local config
git config --unset core.symlinks

# reset the current branch to recreate the missing symbolic links (alternatively it is also possibly to switch branches away and back)
git reset --hard
the Developer Mode has to be enabled first. Then the following commands can be used to enable symbolic links in Git and recreating the symbolic links:

# enable core.symlinks config
git config --global core.symlinks true

# check the current core.sysmlinks config and scope
git config --show-scope --show-origin core.symlinks

# in case the core.sysmlinks config is still set locally to false, remove the local config
git config --unset core.symlinks

# reset the current branch to recreate the missing symbolic links (alternatively it is also possibly to switch branches away and back)
git reset --hard

About Developer Mode check:https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
About symbolic links, check: https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks
