### ISSUE TITLE
How to use SqlQueriesSource

### ISSUE THREAD

**Issue by sunrutcon** [datahub-project/datahub#9915]
How to use SqlQueriesSource to generate Column-level Lineage?

Is it posible to load datahub.ingestion.source.sql_queries.SqlQueriesSource into python script and generate lineage?

I've read:
https://blog.datahubproject.io/extracting-column-level-lineage-from-sql-779b8ce17567
https://datahubproject.io/docs/generated/ingestion/sources/sql-queries/

**Comment by wu-johnson** [comment]
same question, any one can help?

**Comment by sunrutcon** [comment]
So you need running web app to use this feature?
Is it possible to generate sql column level lineage with just importing SqlQueriesSource from the module and do it offilne?

**Comment by hsheth2** [comment]
The docs are more up to date if you select "next" in the version selector

This source needs access to datahub's backend in order to fetch schema information for tables - otherwise the accuracy will be lower.

There was a bug with our processing of certain `insert into` statements, so that query should generate lineage with the latest rc (0.12.1.6rc5) release of acryl-datahub

I'm going to close this issue for now, but feel free to ask any additional questions.
